"""
Pydantic v2 models for the User Management API.

Three models cover the full lifecycle of a user record:

* :class:`UserRecord`  — complete row representation (all DB columns).
* :class:`UserCreate`  — fields required to register a new user.
* :class:`UserUpdate`  — mutable fields that a caller may update.

All models are configured with ``from_attributes=True`` so that asyncpg
``Record`` objects can be validated directly via ``model_validate(row)``.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class UserRecord(BaseModel):
    """Full representation of a row in the ``users`` table.

    Attributes
    ----------
    id:
        Surrogate primary key (UUID v4, generated by the database).
    email:
        Unique e-mail address (max 255 chars).
    display_name:
        Human-readable name shown in the UI (max 100 chars).
    hashed_pw:
        bcrypt-hashed password — **never** returned in API responses.
    is_active:
        Soft-delete flag; ``False`` means the account is deactivated.
    created_at:
        Timestamp of account creation (set by the database).
    updated_at:
        Timestamp of the last modification (set by the database).
    """

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    email: str
    display_name: str
    hashed_pw: str
    is_active: bool
    created_at: datetime
    updated_at: datetime


class UserCreate(BaseModel):
    """Payload for registering a new user.

    Attributes
    ----------
    email:
        Unique e-mail address for the account.
    display_name:
        Human-readable name.
    password:
        Plain-text password.  The caller is responsible for hashing before
        inserting into the database.
    """

    model_config = ConfigDict(from_attributes=True)

    email: str
    display_name: str
    password: str  # plain text — must be hashed before persistence


class UserUpdate(BaseModel):
    """Payload for updating a user record.

    Only ``display_name`` is exposed for mutation; all other fields are
    managed internally (e.g. ``updated_at`` via a DB trigger, ``is_active``
    via the soft-delete endpoint).

    Attributes
    ----------
    display_name:
        New display name.  ``None`` means *no change*.
    """

    model_config = ConfigDict(from_attributes=True)

    display_name: str | None = None
